<?php

namespace Austin\PipelineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * thingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class thingRepository extends EntityRepository
{
}
