austin_trigger:
    resource: "@AustinTriggerBundle/Resources/config/routing.yml"
    prefix:   /
    
austin_pipeline:
    resource: "@AustinPipelineBundle/Resources/config/routes.yml"
    prefix:   /
    
_dashboard:
    path:      /
    defaults:  { _controller: AustinPipelineBundle:Default:index }

