austin_trigger:
    resource: "@AustinTriggerBundle/Resources/config/routing.yml"
    prefix:   /

austin_pipeline:
    resource: "@AustinPipelineBundle/Controller/"
    type:     annotation
    prefix:   /

