defaults:
    path:      /tracker/{name}/{countChange}/{direction}
    defaults: { _controller: AustinPipelineBundle:Default:tracker}
    
visuals:
    path:     /visuals/
    defaults: { _controller: AustinPipelineBundle:Visuals:index}
 