parameters:
#    austin_trigger.example.class: Austin\TriggerBundle\Example
        #Manager
        class: austin\TriggerBundle\Manager\ThingManager
        #Listener
        class: austin\TriggerBundle\Listener\ThingListener
        #ListenerResolver
        class: austin\TriggerBundle\ListenerResolver\ListenerResolver

services:
        #Manager
        service:
            id:       Austin\TriggerBundle\ThingManager
            class:    Austin\TriggerBundle\ThingManager

        #Listener
        service: 
            id:    ThingListener\preUpdate
            class:    ThingListener


        #Listener Resolver
        service: 
            id:       ListenerResolver
            class:    ListenerResolver
            

        service:
            id: kernel.listener.RequestListener
            class: Austin\TriggerBundle\Listeners\RequestListener
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            
        service:
        kernel.listener.ExceptionListener:
            class: Austin\TriggerBundle\Listeners\ExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

